start of the community center
Swofty-Developments/HypixelSkyBlock pull request #289
Opened 2024-04-25 19:37 UTC by ItzKatze

- added Bits-Shop
- added Booster Cookie Shop
- (small) added layout of the bestiary page

2024-04-25 19:46 UTC, Swofty-Developments requested changes

2024-04-25 19:46 UTC, Swofty-Developments commented on type-village/src/main/java/net/swofty/type/village/gui/elizabeth/GUIBitsShop.java
> +        int index3 = 0;
fix variable names

2024-04-25 19:46 UTC, Swofty-Developments commented on type-village/src/main/java/net/swofty/type/village/gui/elizabeth/GUIBitsShop.java
> +                index2++;
fix variable names

2024-04-25 19:46 UTC, Swofty-Developments commented on type-village/src/main/java/net/swofty/type/village/gui/elizabeth/GUIBitsShop.java
> +        int index2 = 0;
fix variable names

2024-04-25 19:46 UTC, Swofty-Developments commented on type-village/src/main/java/net/swofty/type/village/gui/elizabeth/GUIBitsShop.java
> +            index3++;
fix variable names

2024-04-26 18:45 UTC, ItzKatze commented on type-village/src/main/java/net/swofty/type/village/gui/elizabeth/GUIBitsShop.java
> +        int index3 = 0;
done

2024-04-26 18:45 UTC, ItzKatze commented on type-village/src/main/java/net/swofty/type/village/gui/elizabeth/GUIBitsShop.java
> +                index2++;
done

2024-04-26 23:31 UTC, merged